before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: "float"
    binary: "float"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
- image_templates:
  - 'ghcr.io/aaqaishtyaq/float:{{ .Tag }}-amd64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
  extra_files:
  - float.sample.yml
- image_templates:
  - 'ghcr.io/aaqaishtyaq/float:{{ .Tag }}-arm64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm64"
  goarch: arm64
  extra_files:
  - float.sample.yml

docker_manifests:
- name_template: 'ghcr.io/aaqaishtyaq/float:{{ .Tag }}'
  image_templates:
  - 'ghcr.io/aaqaishtyaq/float:{{ .Tag }}-amd64'
  - 'ghcr.io/aaqaishtyaq/float:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/aaqaishtyaq/float:latest'
  image_templates:
  - 'ghcr.io/aaqaishtyaq/float:{{ .Tag }}-amd64'
  - 'ghcr.io/aaqaishtyaq/float:{{ .Tag }}-arm64'
